import java.util.Scanner;
public class Main2b{
    public static void main(String[]args){
        Scanner sc =new Scanner(System.in);
        System.out.println("Enter the energy generated by rooftop solar system in kwh : ");
        double energy =sc.nextDouble();
        if(energy>=10){
            System.out.println("Good Energy Generation");
        }else{
            System.out.println("Low Energy Generation");
        }
    }
}